import os

# Log to HTML conversion function with styling
def log_to_html(log_file, html_file):
    with open(log_file, 'r') as log:
        lines = log.readlines()

    with open(html_file, 'w') as html:
        html.write("""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Behave Test Report</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    margin: 0;
                    padding: 0;
                    background-color: #f4f4f4;
                }
                header {
                    background-color: #333;
                    color: white;
                    text-align: center;
                    padding: 20px 0;
                }
                header h1 {
                    margin: 0;
                }
                .container {
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    min-height: 80vh;
                    padding: 20px;
                }
                .log-content {
                    background-color: white;
                    border-radius: 8px;
                    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                    padding: 20px;
                    width: 80%;
                    max-height: 70vh;
                    overflow-y: auto;
                }
                pre {
                    font-family: monospace;
                    white-space: pre-wrap;
                    word-wrap: break-word;
                    background-color: #f9f9f9;
                    padding: 15px;
                    border-radius: 5px;
                    color: #333;
                }
                footer {
                    background-color: #333;
                    color: white;
                    text-align: center;
                    padding: 10px 0;
                    position: fixed;
                    bottom: 0;
                    width: 100%;
                }
            </style>
        </head>
        <body>
            <header>
                <h1>Behave Test Report</h1>
            </header>

            <div class="container">
                <div class="log-content">
                    <pre>
        """)

        # Escape special HTML characters
        for line in lines:
            escaped_line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            html.write(escaped_line)

        # Close tags for HTML
        html.write("""
                    </pre>
                </div>
            </div>

            <footer>
                <p>Generated by Behave on a test suite run</p>
            </footer>
        </body>
        </html>
        """)

    print(f"HTML report generated: {html_file}")

# Behave hook: After all tests are run
def after_all(context):
    log_file = "output.log"  # Log file produced by Behave
    html_file = "report.html"  # Output HTML file

    # Generate the HTML report
    log_to_html(log_file, html_file)
